{% set name = "grip-nulling" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/grip_nulling-{{ version }}.tar.gz
  sha256: 61aca8ec1940cc67e014c68ff2ba2b7e2ce0de173164b0ccdf4bd5632e136e5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.26.2
    - scipy >=1.11.4
    - matplotlib-base >=3.6.3
    - h5py >=3.8.0
    - emcee >=3.1.4
    - numdifftools >=0.9.41
    - astropy >=5.2.1

test:
  imports:
    - grip
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mamartinod/grip
  summary: Self-calibration data reduction tools for nulling interferometry
  description: |
   GRIP is a novel data reduction methods providing self-calibrated methods for nulling interferometry.
   Check https://github.com/mamartinod/grip for more information
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://grip.readthedocs.io/

extra:
  recipe-maintainers:
    - mamartinod
